# This config creates a deployment with two pods. The pods are configured
# with a request of 200m CPU and 100Mi memory, and a limit of 600m CPU and
# 300Mi memory.
# It also creates a corresponding Vertical Pod Autoscaler that adjusts the
# resources.
# Note that the update mode is left unset, so it defaults to "Auto" mode.
---
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: apache-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: apache-deployment
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 10m
          memory: 50Mi
        maxAllowed:
          cpu: 600m
          memory: 300Mi
        controlledResources: ["cpu", "memory"]
        
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  type: NodePort
  selector:
    app: apache-deployment
  ports:
    - name: http
      port: 80
      targetPort: 80
  externalTrafficPolicy: Local

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache-deployment
  template:
    metadata:
      labels:
        app: apache-deployment
    spec:
      containers:
        - name: apache-container
          image: registry.k8s.io/hpa-example
          resources:
            requests:
              cpu: "200m"
              memory: "100Mi"
            limits:
              cpu: "600m"
              memory: "300Mi"
          ports:
            - containerPort: 80
